const UserService = require('../services/UserService');
const UserError = require('../exceptions/UserError');

const getUserProfileByJwt = async (req, res) => {
    try {
        
        const user = await req.user;
        return res.status(200).json(user);
    } catch (err) {
        handleErrors(err, res);
    }
};

const getUserByEmail = async (req, res) => {
    const { email } = req.query; 
    try {
        const user = await UserService.findUserByEmail(email);
        return res.status(200).json(user);
    } catch (err) {
        handleErrors(err, res);
    }
};


const handleErrors = (err, res) => {
    if (err instanceof UserError) {
        return res.status(404).json({ message: err.message });
    }
    return res.status(500).json({ message: 'Internal Server Error' });
};

// Export the controller methods
module.exports = {
    getUserProfileByJwt,
    getUserByEmail,
};
